export const REGISTER_USER='registeruser';
export const LOGIN_USER="login_user"
export const logoutuser="logout"
export const ADDDETAIL="adddetails"
export const ADDRECORD="addrecord"
export const GETRECORD="getrecord"
export const  AUTH_USER="authuser"
export const  ALLALUM="allalum"
export const  PASS="pass"
export const SEARCHYR="searchyr"
export const ADDAWARD="addaward"
export const ALLAWARDS="allawards"
export const  FORGET="forget"
export const ADDEDUCATION="addeducation"
export const WRITEUSER="writeuser"
export const ENDSESSION="endsession"
export const ADDSKILL="addskill"

export const ADDACADEMIC="addacademic"
export const ALLACADEMIC="allacademic"
export const EDITDATA="editdata"

export const SET_HEADER="setheaders"